[profile.default]
src = "src"
out = "out"
libs = ["lib"]

evm_version="shanghai"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-06/=lib/openzeppelin-contracts-06/",
    "@openzeppelin-08/=lib/openzeppelin-contracts-08/",
]

eth_rpc_url = 'wss://ethereum-sepolia-rpc.publicnode.com'
etherscan_api_key = '${ETHERSCAN_KEY}'